#
#   SN-11 Agent Training Configuration
#
#   Find documentation on what these parameters mean here:
#   https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Training-Configuration-File.md
#
#   Authored By Ryan Maugin (@ryanmaugv1)
#

# TODO: Add demo for behavioural cloning to speed up training.

behaviors:
  SN-11:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 1024
      learning_rate: 3.0e-4
      beta: 0.01
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 100000000
    time_horizon: 64
    summary_freq: 10000